#baseURL = "https://thomaslacour.github.io/blib/"
baseURL = "https://festivalbieresbordeaux.fr/"
title = "Festival BLIB"
languageCode = "fr-FR"
defaultContentLanguage = "fr"
paginate = "7"
theme = "blib"
enableEmoji = true
#googleAnalytics = "G-XXXXXXXXXX"

################################################################################
# TOP
################################################################################

[params]
fancyTitle = "FESTIVAL BLiB" # title for frontpage, may include image
logo = "images/bliby_rond.png"
copyright = "Festival BLIB"
description = '''
Le BLIB fête ses 10 ans !<br>
<a href="posts/events">Évènements du 14 au 19 avril</a> <br>
Le grand final au H14 : <a href="posts/h14">samedi 19 avril</a>
'''
startbuttonText = "Je prends ma place !"
startbuttonLink = "https://www.helloasso.com/associations/blib/evenements/prevente-blib-2025-au-hangar-14"
body_is_markdown = true
# extrabuttonText = "Concours brassam"
# extrabuttonLink = "posts/brassam"
#custom_css = "foo.css"
#custom_sass = "bar.scss"
# images = ["path_to_social_image_for_link_previews.jpg"]

################################################################################
# MENU
################################################################################

[[params.menu.main]]
url = '/'
title = "Festival BLIB"

[[params.menu.main]]
url = '/posts/events'
title = "Semaine du BLIB"

[[params.menu.main]]
url = '/posts/h14'
title = "Final au H14"

# [[params.menu.main]]
# url = '/posts/brassam'
# title = "Concours Brassam"

[[params.menu.main]]
url = 'https://forms.gle/BjCg2zdzeX7VBZTh8'
title = "Devenir Bénévole"

[[params.menu.main]]
url = 'https://drive.google.com/file/d/1aj4r36f6ez3T8O01BdShOE9MQazFAti1/view?usp=sharing'
title = "Dossier de presse"

[[params.menu.main]]
url = '/posts/galerie'
title = "Galeries"

[[params.menu.main]]
url = '/posts/faq'
title = "FAQ"

[[params.menu.main]]
url = '/posts/preventions'
title = "Prévention & Modération"

[[params.menu.main]]
url = '/posts/partenaires'
title = "Nos partenaires"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

################################################################################
# TOP INFOS
################################################################################

[params.one]
enable = true
title = 'Bières Libres & Indépendantes à Bordeaux'
body = '''
Le BLIB est le 1er festival bordelais dédié à la bière artisanale.

Créé en 2015, l’association est menée par un collectif regroupant professionnels indépendants et particuliers, amateurs et connaisseurs du monde brassicole.

Le BLIB a su réunir des brasseries artisanales engagées et un public diversifié dans différents lieux de la métropole qui soutiennent la bière artisanale : bars, caves, restaurants, brasseries etc.
Des dégustations, des rencontres, des ateliers, des conférences.
'''

# [[params.one.icon]]
# icon = "fa-beer"
# style = "1"
# label = "Lorem"

# [[params.one.icon]]
# icon = "fa-heart"
# style = "2"
# label = "Ipsum"

# [[params.one.icon]]
# icon = "solid fa-code"
# style = "3"
# label = "Dolor"

################################################################################
# MIDDLE INFOS
################################################################################

[params.two]
enable = true

[[params.two.section]]
img = "images/visuel_blib2.jpg"
img_alt = "blurry background: white/grey"
title = '6 jours de festivités'
body = "Le BLIB se déroule en région Bordelaise sur un ensemble d'évènements ponctuels du lundi au vendredi et il se termine par un grand final le samedi"

[[params.two.section]]
img = "images/visuel_blib4.png"
title = '30 lieux partenaires'
body = "Un trentaine de lieux partenaires (brasserie, bar, cave, restaurant ...) s'associent chaque année avec nous pour vous proposer des évènements variés autour de la biére (découverte et dégustation) !"

[[params.two.section]]
img = "images/visuel_blib3.png"
title = '70 exposants'
body = '''
Lors du grand final qui se déroule depuis plusieurs années au Hangar 14, tous les exposants, des brasseries aux partenaires de la restauration, se retrouvent pour célébrer la bière craft
'''

################################################################################
# EXPOSANTS
################################################################################
# remove bg: https://www.remove.bg/fr/upload

[params.three]
enable = true
title = 'Exposants 2025'
# body = '''
# '''

# TEMPLATE
#[[params.three.feature]]
#icon = "fa-paper-plane"
#title = "Title"
#body = "body"
# todo (not supported within the template)
#img = "..."

[[params.three.feature]]
title = "Azimut"
body = "Bordeaux (33), France"
link = "https://www.azimutbrasserie.com/"
icon = "test"
logo = "images/logos/azimut.png"

[[params.three.feature]]
title = "Bee King"
body = "Saint Priest (69), France"
link = "https://www.beeking.fr/"
logo = "images/logos/beeking.png"

[[params.three.feature]]
title = "Moustous"
body = "Cours-les-Bains (33), France"
link = "https://www.facebook.com/FermeBrasserieMoustous"
logo = "images/logos/moustous.png"

[[params.three.feature]]
title = "KAPSYL"
body = "Chambray-lés-Tours (37), France"
link = "https://www.instagram.com/brasseriekapsyl/"
logo = "images/logos/kapsyl.png"

[[params.three.feature]]
title = "Jukebox"
body = "Cognac (16), France"
link = "https://brasseriejukebox.com/"
logo = "images/logos/jukebox.png"

[[params.three.feature]]
title = "Effet Papillon"
body = "Mérignac (33), France"
link = "https://www.brasserieffetpapillon.com/"
logo = "images/logos/pap.png"

[[params.three.feature]]
title = "Maison PIP"
body = "Bègles (33), France"
link = "https://maisonpip.com/"
logo = "images/logos/pip.png"

[[params.three.feature]]
title = "La Gang"
body = "Biscarrosse (40), France"
link = "https://lagang.fr/"
logo = "images/logos/gang.png"

[[params.three.feature]]
title = "Rosny"
body = "Seignoss (40), France"
link = "https://www.rosny-beer.com/"
logo = "images/logos/rosny.png"

# [[params.three.feature]]
# title = "Sidras"
# body = "Nantes (44), France"
# link = "https://www.sidras.fr/"
# logo = "images/logos/sidras.png"

[[params.three.feature]]
title = "Mūrbūdu"
body = "Letonie"
link = "https://www.murbuduveikals.lv/"
logo = "images/logos/murbudu.png"

[[params.three.feature]]
title = "La Galotière"
body = "Crouttes (61), France"
link = "https://www.lagalotiere.fr/"
logo = "images/logos/galotiere.png"

[[params.three.feature]]
title = "Zebra"
body = "Preignac (33), France"
link = "https://brasseriezebra.fr/"
logo = "images/logos/zebra.png"

[[params.three.feature]]
title = "Burdigala"
body = "Bordeaux (33), France"
link = "https://www.bieredebordeaux.com/"
logo = "images/logos/burdigala.png"

[[params.three.feature]]
title = "Le bercail WUB"
body = "St-Magne-de-Castillon (33), France"
link = "https://lebercail-wub.fr/"
logo = "images/logos/wub.png"

[[params.three.feature]]
title = "Brasseurs Cueilleurs"
body = "Landrais (17), France"
link = "https://brasseurscueilleurs.fr/"
logo = "images/logos/cueilleurs.png"

[[params.three.feature]]
title = "DWYN"
body = "Montagny (67), France"
link = "https://www.dwynbrewing.com/"
logo = "images/logos/dwyn.png"

[[params.three.feature]]
title = "Arcka"
body = "Gières (38), France"
link = "https://brasserie-arcka.fr/"
logo = "images/logos/arcka.svg"

# [[params.three.feature]]
# title = "Bam"
# body = "Périgueux (24), France"
# link = "https://www.bam-brasserie.fr/"
# logo = "images/logos/bam.png"

[[params.three.feature]]
title = "Blind Pigs"
body = "Pau (64), France"
link = "https://www.blindpigs.fr/"
logo = "images/logos/blindpigs.png"

[[params.three.feature]]
title = "Blue Coast"
body = "Nice (06), France"
link = "https://bluecoastbrewing.com/"
logo = "images/logos/bluecoast.jpeg"
#
# [[params.three.feature]]
# title = "Boerenerf"
# body = "Belgique"
# link = "https://www.boerenerf.bio/"
# logo = "images/logos/boerenerf.png"

[[params.three.feature]]
title = "Bruel"
body = "Tarnos (40), France"
link = "https://brasseriebruel.fr/"
logo = "images/logos/bruel.png"

[[params.three.feature]]
title = "Brunack"
body = "Assac-sur-Vienne (16), France"
link = "https://brunack.com/"
logo = "images/logos/brunack.png"

[[params.three.feature]]
title = "Chubby Brew"
body = "Bouafle (78), France"
link = "https://www.instagram.com/chubbybrewing/"
logo = "images/logos/chubbybrew.png"

[[params.three.feature]]
title = "Drunk Beard"
body = "Morrens, Suisse"
link = "https://drunkbeard.ch/"
logo = "images/logos/drunkbeard.png"

[[params.three.feature]]
title = "Fauve"
body = "Montpellier (34), France"
link = "https://fauvebiere.com/"
logo = "images/logos/fauve.png"

[[params.three.feature]]
title = "Fusion"
body = "Bourgbarré (35), France"
link = "https://www.instagram.com/fusionbrasserie_/"
logo = "images/logos/fusion.png"

[[params.three.feature]]
title = "Gekko"
body = "Tourrettes (83), France"
link = "https://www.gekkobeers.com/"
logo = "images/logos/gekko.png"

[[params.three.feature]]
title = "Gentlemen Pirates"
body = "Nantes (44), France"
link = "https://gentlemenpirates.my.canva.site/"
logo = "images/logos/pirates.png"

# [[params.three.feature]]
# title = "Hoodo"
# body = "Tarare (69), France"
# link = "https://hoodo.fr/"
# logo = "images/logos/hoodo.png"

[[params.three.feature]]
title = "Horla"
body = "Grand-Champ (56), France"
link = "https://www.facebook.com/microbrasseriehorla/"
logo = "images/logos/horla.png"

[[params.three.feature]]
title = "Juliens B.Ale"
body = "Blanquefort (33), France"
link = "https://brasserie-juliens.fr/biere-b-ale/"
logo = "images/logos/bale.png"

[[params.three.feature]]
title = "L'Instant"
body = "Pontault-Combo (77), France"
link = "https://bieres-linstant.fr/"
logo = "images/logos/linstant.png"

[[params.three.feature]]
title = "La Bestiole"
body = "Saint-Barthélemy-d'Anjou (49), France"
link = "https://www.brasserielabestiole.fr/"
logo = "images/logos/bestiole.png"

[[params.three.feature]]
title = "Piggy"
body = "Liverdun (54), France"
link = "https://thepiggybrewingcompany.com/"
logo = "images/logos/piggy.png"

[[params.three.feature]]
title = "La Superbe"
body = "Anglet (64), France"
link = "https://www.lasuperbe.fr/"
logo = "images/logos/lasuperbe.png"

[[params.three.feature]]
title = "La Chouette"
body = "St-Jean-de-Muzols (64), France"
link = "https://www.instagram.com/la_chouette_brasserie/"
logo = "images/logos/lachouette.png"

[[params.three.feature]]
title = "Smash"
body = "Rennes (35), France"
link = "https://smash.bzh/"
logo = "images/logos/smash.png"

[[params.three.feature]]
title = "Sauvage"
body = "St-Jacues-de-la-Lande (35), France"
link = "https://www.brasseriesauvage.co/"
logo = "images/logos/sauvage.jpg"

[[params.three.feature]]
title = "Nautile"
body = "Rezé (44), France"
link = "https://brasserienautile.com/"
logo = "images/logos/nautile.png"

[[params.three.feature]]
title = "Sake Chevalier"
body = "Capbreton (40), France"
link = "https://www.brasseriechevalier.com/"
logo = "images/logos/sakechevalier.png"

[[params.three.feature]]
title = "Little Atlantique"
body = "Nantes (44), France"
link = "https://little-atlantique-brewery.fr/"
logo = "images/logos/littleatlantique.png"

[[params.three.feature]]
title = "Noktua Brama"
body = "Saint-Estèphe (33), France"
link = "https://www.facebook.com/p/Micro-brasserie-Noktua-Brama-61565516728876/"
logo = "images/logos/noktuabrama.png"

[[params.three.feature]]
title = "La Fracasse Coquille"
body = "Libourne (33), France"
link = "https://la-fracasse-coquille.fr/"
logo = "images/logos/fracasse.png"

[[params.three.feature]]
title = "La Tute"
body = "Nousty (64), France"
link = "http://bieres-lagrange.fr/"
logo = "images/logos/latute.png"

[[params.three.feature]]
title = "Salama"
body = "Finlande"
link = "https://www.salamabrewing.com/"
logo = "images/logos/salama.png"

[[params.three.feature]]
title = "Landberry"
body = "Anglet (64), France"
link = "https://landberry.fr/"
logo = "images/logos/landberry.png"

[[params.three.feature]]
title = "Pyraser"
body = "Allemagne"
link = "https://www.pyraser.de/"
logo = "images/logos/pyraser.svg"

[[params.three.feature]]
title = "La P'tite Maiz"
body = "Notre-Dame-D'Oé (37), France"
link = "https://www.laptitemaiz.com/"
logo = "images/logos/maiz.png"

[[params.three.feature]]
title = "Borinage"
body = "Belgique"
link = "https://brasserieduborinage.be/"
logo = "images/logos/borinage.png"

[[params.three.feature]]
title = "Bouillant"
body = "Fleurey-sur-Ouche (21), France"
link = "https://brasseriebouillant.fr/"
logo = "images/logos/bouillant.png"

[[params.three.feature]]
title = "Bouquier"
body = "Ludon-Médoc (33), France"
link = "https://www.azatobu.com/bouquier/"
logo = "images/logos/bouquier.png"

[[params.three.feature]]
title = "Brasserie Dac"
body = "Tarnos (33), France"
link = "https://www.instagram.com/brasserie_dac/"
logo = "images/logos/dac.png"

[[params.three.feature]]
title = "Eighty One"
body = "Soual (81), France"
link = "https://www.eightyonebrewing.fr/"
logo = "images/logos/81.png"

[[params.three.feature]]
title = "La Canaulaise"
body = "Lacanau (33), France"
link = "https://www.lacanaulaise.com/"
logo = "images/logos/canaulaise.png"

[[params.three.feature]]
title = "La Débauche"
body = "Angoulème (16), France"
link = "https://www.brasserie-ladebauche.com/"
logo = "images/logos/debauche.png"

[[params.three.feature]]
title = "La Lune"
body = "Bordeaux (33), France"
link = "https://brasseurs-lalune.fr/"
logo = "images/logos/lune.png"

[[params.three.feature]]
title = "Maltolab"
body = "Gommerville (28), France"
link = "https://www.instagram.com/brasserie_maltolab/"
logo = "images/logos/maltolab.png"

[[params.three.feature]]
title = "Merlin"
body = "Pen'March (29), France"
link = "https://www.merlin.beer/"
logo = "images/logos/merlin.png"

[[params.three.feature]]
title = "Moersleutel"
body = "Pays-Bas"
link = "https://moersleutel.com/"
logo = "images/logos/moersleutel.png"

[[params.three.feature]]
title = "Parallele"
body = "Floirac (33), France"
link = "https://www.facebook.com/p/Micro-brasserie-Noktua-Brama-61565516728876/"
logo = "images/logos/parallele.png"

[[params.three.feature]]
title = "Schlag"
body = "Castelnau-De-Mandailles (12), France"
link = "https://www.instagram.com/schlag.brastylerie/"
logo = "images/logos/schlag.png"

[[params.three.feature]]
title = "Second Degré"
body = "Magny-Le-Hongre (77), France"
link = "https://www.instagram.com/microbrasserie_seconddegre"
logo = "images/logos/second.png"

[[params.three.feature]]
title = "Spore"
body = "Gravigny (27), France"
link = "https://www.brasserie-spore.com/"
logo = "images/logos/spore.png"

[[params.three.feature]]
title = "Tipsip"
body = "Brassy (58), France"
link = "https://www.tipsip.fr/"
logo = "images/logos/tipsip.png"

[[params.three.feature]]
title = "Uncle"
body = "Etables-sur-Mer (22), France"
link = "https://www.brasserie-uncle.com/"
logo = "images/logos/uncle.png"

[[params.three.feature]]
title = "Winterholer"
body = "Villenave D'Ornon (33), France"
link = "https://brasserie.bio/"
logo = "images/logos/winter.png"

[[params.three.feature]]
title = "Witty Kitty"
body = "Escalquens (31), France"
link = "https://www.thewittykitty.fr/"
logo = "images/logos/kitty.png"

[[params.three.feature]]
title = "Haacht"
body = "Belgique"
link = "https://haacht.com/"
logo = "images/logos/haacht.jpg"

[[params.three.feature]]
title = "Overground"
body = "Strasbourg (67), France"
link = "https://www.instagram.com/overgroundbrewing"
logo = "images/logos/overground.png"

[[params.three.feature]]
title = "Boneless"
body = "Châtillon (92), France"
link = "http://www.bonelessbrewing.com/"
logo = "images/logos/boneless.png"

# ################################################################################
# # BRASSAM
# ################################################################################
#
# [params.cta]
# enable = true
# title = "Concours brassam"
# body = "Le concours brassam récompense chaque année le meilleur brassage amateur réalisé pour l'occasion du festival"
#
# [[params.cta.link]]
# href = "https://forms.gle/oZyWM27vs234TbDY6"
# text = "Inscription"
# special = true
#
# [[params.cta.link]]
# href = "https://drive.google.com/file/d/166EJDwHGwuAf2WTE6JxzsovlPb4VwVIo/view"
# text = "Informations"
# special = false

################################################################################
# CONTACT
################################################################################

[params.contact]
email = "asso.blib@gmail.com"
enable = false
# title = "Contacter"
# body = "Hello le BLIB!"
#phone = "+49 (0) 030 000 000"
address = "Bordeaux"
# subject = "New Submission!"
# formspree_form_id = "example_invalid"

################################################################################
# SOCIAL
################################################################################

[params.social]
twitter = ""
mastodon = ""
github = ""
facebook = "AssoBLIB"
youtube = ""
instagram = "festival_blib"
dribble = ""
helloasso = "blib"  ##todo

################################################################################
# LEGAL
################################################################################

[params.legal]
name = "Association BLIB"
address = "111 rue Lagrange -- 33000 Bordeaux"
contact = "asso.blib[at]gmail.com"
website = "SAS Github France, 37 Quai du Président Roosevelt (92130) Issy-Les-Moulineaux"
comment = "Nos évènements sont interdits aux mineurs non accompagné d’une personne majeure. L'abus d'alcool est dangereux pour la santé, à consommer avec modération"

# language specific options

[languages.fr]
weight = 0
languageName = "French"

# [languages.en]
# weight = 0
# languageName = "English"
#
# [languages.de]
# weight = 10
# languageName = "Deutsch"
#
# [languages.es]
# weight = 10
# languageName = "Español"
